#pragma config(Motor,  port1,           leftWheel,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           rightWheel,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           middleWheel,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          sonicSensor,   tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define FULLPWR 127
#define HALFPWR 63
#define QTRPWR 32

//create functions up here


task main()
{
	int speed;
	int sonar_value;
	int distance = 25;

	while(true)
	{
		sonar_value = SensorValue(sonicSensor);

		clearLCDLine(0)
		displayLCDPos(0,0);
		displayNextLCDString("Sonar: ");
		displayNextLCDNumber(sonar_value);

		if(sonar_value < 0) //out of range of object
		{
			speed = 127;
		}
		else //There is something there and the robot is using this formula to correct it
		{
			speed = (sonar_value - distance)*2;
		}
		//clearing out everything
		clearLCDLine(1);
		displayLCDPos(1,0);
		displayNextLCDString("Speed: ");
		displayNextLCDNumber(speed);
		//assigning speeds to the motors
		motor[leftWheel] = speed;
		motor[rightWheel] = speed;
		motor[middleWheel] = speed;

		wait1Msec(100);
	}
}
