#pragma config(Motor,  motor1,          leftWheel,     tmotorVexIQ, openLoop)
#pragma config(Motor,  motor2,          rightWheel,    tmotorVexIQ, openLoop)
#pragma config(Motor,  motor3,          middleWheel,   tmotorVexIQ, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

#define CHONE vexRT[Ch1] //channels are on the controller
#define CHTWO vexRT[Ch2]
#define CHTHREE vexRT[Ch3]
#define CHFOUR vexRT[Ch4]

#define FULLPWR 127
#define HALFPWR 63
#define QTRPWR 32


/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
	/*
	//frontDrive(FULLPWR, 9000);
	//code to close the claw first thing
	mobileLiftUp(-FULLPWR,550);
	frontDrive(HALFPWR, 5500);
	mobileLiftUp(FULLPWR, 200);
	armDown(FULLPWR);
	clawOpen(-FULLPWR);

	frontDrive(-HALFPWR, 4000);
	// move diagonally for abt 2-3 sec
	sideDrive(HALFPWR, 4000);
	*/
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{

  while (true)
  {
    // This is the main execution loop for the user control program.
    // Each time through the loop your program should update motor + servo
    // values based on feedback from the joysticks.
    //motor power levels range from -127 (full reverse) to 0 (stopped) to 127 (full power)

    //sets each of the wheel/chassis motors to a channel on the joystick
		motor[leftWheel] =  CHTWO;
		motor[rightWheel] =  CHTWO;
		motor[middleWheel] =  CHONE;

		//claw moves one direction when button 7D pressed
		if (vexRT[Btn7D] == 1)
		{
			motor[claw] = HALFPWR; //motor forward for about half power
		}
		else if (vexRT[Btn7L] == 1)
	  {
		 motor[claw] = -HALFPWR; //claw moves in opposite direction when button 7L pressed
  	}
		else
		{
			motor [claw] = 0;
  	}

  	//arm moves one direction when button 6D pressed
		if (vexRT[Btn6D] == 1)
		{
				motor[arm] = -HALFPWR; //motor forward for about half power
		}
		else if (vexRT[Btn6U] == 1)
	  {
	  		motor[arm] = HALFPWR; //arm moves in opposite direction when button 6U pressed
  	}
		else
		{
			motor [arm] = 0;
  	}


  	//goal lift
  	if (vexRT [Btn5U] == 1)
    {
    	motor[mobileLift] = HALFPWR;
    }
    else if (vexRT[Btn5D] == 1)
    {
    	motor[mobileLift] = -HALFPWR;
		}
		else
		{
			motor[mobileLift] = 0;
		}


  	//controlls the winding up and unwinding of the winch
  	if (vexRT [Btn7U] == 1)
    {
    	motor[leftWinch] = HALFPWR;
    	motor[rightWinch] = -HALFPWR;
    }
    else if (vexRT[Btn7R] == 1)
    {
    	motor[leftWinch] = -QTRPWR;
    	motor[rightWinch] = QTRPWR;
		}
		else
		{
			motor[leftWinch] = 0;
			motor[rightWinch] = 0;
		}
  }
}
